#!/bin/bash

###############################################################################
# Handle options
###############################################################################

# Display the help
if [ "${1:-}" = "-h" ] || [ "${1:-}" = "--help" ]; then
  echo -e "
Get the name of the branch you're currently on.

\e[33mUsage:\e[0m
  git currentbranch

\e[33mOptions:\e[0m
\e[32m  -h, --help \e[0m Display this help message
"
  exit 0;
fi


###############################################################################
# Script
###############################################################################

git symbolic-ref --short HEAD
